name = "MyGraph"
uuid = "4404a3e4-8e19-41a3-af2a-c632de2af867"
authors = ["Patrik Drbal <drbalpat@fit.cvut.cz> and contributors"]
version = "0.1.0"

[deps]
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
